# Week 3 - Data Visualization
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
# loading cleaned data
df = pd.read_csv('cleaned_aqi_data.csv')
# setting style for better looking plots
sns.set_style("whitegrid")
print("Creating visualizations...\n")
# 1. City-wise average AQI comparison (Bar Chart)
print("1. Creating city comparison bar chart...")
plt.figure(figsize=(10, 6))
city_avg = df.groupby('City')['AQI'].mean().sort_values(ascending=False)
plt.bar(city_avg.index, city_avg.values, color='coral')
plt.xlabel('City')
plt.ylabel('Average AQI')
plt.title('Average AQI by City')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('chart1_city_comparison.png')
plt.close()
print("   Saved as 'chart1_city_comparison.png'\n")
# 2. Monthly AQI trends (Line Chart)
print("2. Creating monthly trends line chart...")
plt.figure(figsize=(10, 6))
monthly_avg = df.groupby('Month')['AQI'].mean()
plt.plot(monthly_avg.index, monthly_avg.values, marker='o', linewidth=2, color='blue')
plt.xlabel('Month')
plt.ylabel('Average AQI')
plt.title('Monthly AQI Trends')
plt.xticks(range(1, 13))
plt.grid(True)
plt.tight_layout()
plt.savefig('chart2_monthly_trends.png')
plt.close()
print("   Saved as 'chart2_monthly_trends.png'\n")
# 3. Seasonal comparison (Bar Chart)
print("3. Creating seasonal comparison chart...")
plt.figure(figsize=(8, 6))
season_avg = df.groupby('Season')['AQI'].mean()
colors = ['skyblue', 'orange', 'green', 'brown']
plt.bar(season_avg.index, season_avg.values, color=colors)
plt.xlabel('Season')
plt.ylabel('Average AQI')
plt.title('Average AQI by Season')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('chart3_seasonal_comparison.png')
plt.close()
print("   Saved as 'chart3_seasonal_comparison.png'\n")
# 4. Health category distribution (Pie Chart)
print("4. Creating health category pie chart...")
plt.figure(figsize=(8, 8))
health_counts = df['Health_Category'].value_counts()
colors_pie = ['green', 'yellow', 'orange', 'red', 'purple', 'maroon']
plt.pie(health_counts.values, labels=health_counts.index, autopct='%1.1f%%', 
        colors=colors_pie, startangle=90)
plt.title('Distribution of Air Quality Categories')
plt.tight_layout()
plt.savefig('chart4_health_category_pie.png')
plt.close()
print("   Saved as 'chart4_health_category_pie.png'\n")
# 5. City-wise AQI distribution (Box Plot)
print("5. Creating city-wise box plot...")
plt.figure(figsize=(10, 6))
cities = df['City'].unique()
data_to_plot = [df[df['City'] == city]['AQI'].values for city in cities]
plt.boxplot(data_to_plot, labels=cities)
plt.xlabel('City')
plt.ylabel('AQI')
plt.title('AQI Distribution by City')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('chart5_city_boxplot.png')
plt.close()
print("   Saved as 'chart5_city_boxplot.png'\n")
# 6. Heatmap of City vs Season
print("6. Creating city-season heatmap...")
plt.figure(figsize=(10, 8))
pivot_table = df.pivot_table(values='AQI', index='City', columns='Season', aggfunc='mean')
sns.heatmap(pivot_table, annot=True, fmt='.1f', cmap='YlOrRd')
plt.title('Average AQI: City vs Season Heatmap')
plt.tight_layout()
plt.savefig('chart6_city_season_heatmap.png')
plt.close()
print("   Saved as 'chart6_city_season_heatmap.png'\n")
# 7. Yearly trends (if multiple years available)
if 'Year' in df.columns and df['Year'].nunique() > 1:
    print("7. Creating yearly trends chart...")
    plt.figure(figsize=(10, 6))
    yearly_avg = df.groupby('Year')['AQI'].mean()
    plt.plot(yearly_avg.index, yearly_avg.values, marker='o', linewidth=2, color='darkgreen')
    plt.xlabel('Year')
    plt.ylabel('Average AQI')
    plt.title('Year-over-Year AQI Trends')
    plt.grid(True)
    plt.tight_layout()
    plt.savefig('chart7_yearly_trends.png')
    plt.close()
    print("   Saved as 'chart7_yearly_trends.png'\n")
# 8. Hazardous days count by city (Horizontal Bar Chart)
print("8. Creating hazardous days chart...")
plt.figure(figsize=(10, 6))
hazardous_days = df[df['Health_Category'] == 'Hazardous'].groupby('City').size().sort_values()
plt.barh(hazardous_days.index, hazardous_days.values, color='darkred')
plt.xlabel('Number of Hazardous Days')
plt.ylabel('City')
plt.title('Hazardous Days Count by City')
plt.tight_layout()
plt.savefig('chart8_hazardous_days.png')
plt.close()
print("   Saved as 'chart8_hazardous_days.png'\n")
# 9. AQI histogram
print("9. Creating AQI distribution histogram...")
plt.figure(figsize=(10, 6))
plt.hist(df['AQI'], bins=30, color='teal', edgecolor='black')
plt.xlabel('AQI Value')
plt.ylabel('Frequency')
plt.title('Distribution of AQI Values')
plt.axvline(df['AQI'].mean(), color='red', linestyle='--', label='Mean')
plt.axvline(df['AQI'].median(), color='orange', linestyle='--', label='Median')
plt.legend()
plt.tight_layout()
plt.savefig('chart9_aqi_histogram.png')
plt.close()
print("   Saved as 'chart9_aqi_histogram.png'\n")
# 10. Month-wise comparison for each city
print("10. Creating month-wise city comparison...")
plt.figure(figsize=(12, 6))
for city in df['City'].unique():
    city_data = df[df['City'] == city].groupby('Month')['AQI'].mean()
    plt.plot(city_data.index, city_data.values, marker='o', label=city)
plt.xlabel('Month')
plt.ylabel('Average AQI')
plt.title('Monthly AQI Trends by City')
plt.xticks(range(1, 13))
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig('chart10_monthly_city_comparison.png')
plt.close()
print("   Saved as 'chart10_monthly_city_comparison.png'\n")
# 11. Pollutant comparison (if available)
pollutants = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3']
available_pollutants = [p for p in pollutants if p in df.columns]
if available_pollutants:
    print("11. Creating pollutant comparison chart...")
    plt.figure(figsize=(10, 6))
    avg_pollutants = [df[p].mean() for p in available_pollutants]
    plt.bar(available_pollutants, avg_pollutants, color='purple')
    plt.xlabel('Pollutant')
    plt.ylabel('Average Level')
    plt.title('Average Pollutant Levels')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig('chart11_pollutant_comparison.png')
    plt.close()
    print("   Saved as 'chart11_pollutant_comparison.png'\n")
print("=" * 50)
print("All visualizations created successfully!")
print("Total charts created: 11")
print("Check the current folder for all PNG files")
print("=" * 50)